@startuml
partition Пользователь {
 (*) --> "Ввод данных"
 if "" then
  --> [с монитора или клавиатуры]===B1===
  partition Программа #LightSkyBlue {
  --> "Проверка данных на корректность"
  --> "Создание массива состояний графа"
  }
  --> ===B2===
  ===B1=== --> ===B3===
   --> "Назначить стартовую вершину"
   --> ===B4===
   partition Программа #LightSkyBlue {
   ===B3=== --> "Добавить вершину в граф"
   --> "Визуализовать вершину"
   --> ===B4===
    }
   --> [ ]===B5===
       --> "Введем вершины графа"
       --> ===B6===
       partition Программа #LightSkyBlue {
       ===B5=== --> "Добавим вершины в граф"
       --> "Визуализируем вершины"
       --> ===B6===
       }
   --> [ ]===B7===
   --> "Введем ребра графа"
   --> "Введем вес ребер"
   --> ===B8===
   partition Программа #LightSkyBlue {
   ===B7=== --> "Добавим ребра в граф"
   --> "Визуализируем ребра"
   --> ===B8===
   }
  --> ===B2===
  --> "Просмотр алгоритма"
partition Программа #LightSkyBlue {
 else
  -->[из файла] "Проверка корректности данных"
  if "" then
   partition Пользователь {
    -->[данные корректны] "Просмотр алгоритма"
  else
   -->[данные не корректны] (*)
   endif
    "Просмотр алгоритма" -->  if " " then
       --> "Шаг вперед"
       else
       --> "Шаг назад"
    endif
    "Шаг вперед" --> (*)
    "Шаг назад" --> (*)

}
@enduml