@startuml
       :Пользователь:
       usecase UC1 as "Ввод данных"
       usecase UC6 as "Наблюдать визуализацию
       алгоритма"
       Пользователь -> (UC1)
       (UC1) <|-- (с монитора)
       (UC1) <|-- (с клавиатуры)
       (UC1) <|-- (из файла)
       (из файла) .> (Данные корректны)
       (с клавиатуры) ...> (Данные корректны)
       (UC1) -> (UC6)
       (UC6) <|-- (Делать шаг вперед)
       (UC6) <|-- (Делать шаг назад)
       @enduml